name: Build_Push_Docker_And_Pull_DockerImagee
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ['main']
 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
 
      - name: Login to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: chaituiisc/mlops:v1_ci_cd
          
  pull-docker-image:
    runs-on: ubuntu-latest  
    needs: build-and-push-image
    if: ${{ needs.build-and-push-image.result == 'success' }}
    steps:
      - name: Pull Docker image
        run: docker pull chaituiisc/mlops:v1_ci_cd
 
      - name: Run Docker container and test
        run: |
          OUTPUT=$(docker run chaituiisc/mlops:v1_ci_cd)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.35" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
          echo "successfull executed!"
          
  fail-job:
      runs-on: ubuntu-latest  
      needs: build-and-push-image
      if: ${{ needs.build-and-push-image.result != 'success' }}
      steps:
      - name: fail the jobs as docker image build job is failed
        run: |
          echo "Fail the job since the docker job to build and push docker image job got failed"
          exit 1
